name: CI/CD Pipeline

# Task 1: Basic workflow triggers
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  
  # Task 2: Manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  # Task 1: Basic build and test job
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Display greeting message
      run: |
        echo "Hello, GitHub Actions!"
        echo "This is our first CI/CD pipeline"
        echo "Current date and time: $(date)"
        
    - name: Run basic tests
      run: |
        echo "Running basic tests..."
        echo "✅ All tests passed!"
        
    - name: Build project
      run: |
        echo "Building project..."
        echo "✅ Build completed successfully!"

  # Task 2: System information gathering job
  system-info:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Gather System Information
      run: |
        echo "=== SYSTEM INFORMATION ==="
        echo "Runner OS: $RUNNER_OS"
        echo "Runner Architecture: $RUNNER_ARCH"
        echo "Runner Name: $RUNNER_NAME"
        echo "Runner Tool Cache: $RUNNER_TOOL_CACHE"
        echo ""
        
        echo "=== HARDWARE SPECIFICATIONS ==="
        echo "CPU Information:"
        cat /proc/cpuinfo | grep "model name" | head -1
        echo "CPU Cores: $(nproc)"
        echo ""
        
        echo "Memory Information:"
        free -h
        echo ""
        
        echo "Disk Space:"
        df -h
        echo ""
        
        echo "=== OPERATING SYSTEM DETAILS ==="
        echo "OS Release:"
        cat /etc/os-release
        echo ""
        
        echo "Kernel Version:"
        uname -a
        echo ""
        
        echo "Available Tools:"
        which git && git --version
        which node && node --version
        which npm && npm --version
        which python3 && python3 --version
        which docker && docker --version
        echo ""
        
        echo "Environment Variables:"
        echo "HOME: $HOME"
        echo "PATH: $PATH"
        echo "SHELL: $SHELL"
        echo "USER: $USER"
        
    - name: GitHub Actions Context Information
      run: |
        echo "=== GITHUB ACTIONS CONTEXT ==="
        echo "GitHub Event: ${{ github.event_name }}"
        echo "GitHub Repository: ${{ github.repository }}"
        echo "GitHub Actor: ${{ github.actor }}"
        echo "GitHub SHA: ${{ github.sha }}"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Workflow: ${{ github.workflow }}"
        echo "GitHub Job: ${{ github.job }}"
        echo "GitHub Run ID: ${{ github.run_id }}"
        echo "GitHub Run Number: ${{ github.run_number }}"
        
  # Additional job to demonstrate more CI/CD features
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check file structure
      run: |
        echo "=== PROJECT STRUCTURE ==="
        find . -type f -name "*.md" | head -10
        echo ""
        echo "Total files in repository:"
        find . -type f | wc -l
        echo ""
        echo "Repository size:"
        du -sh .
        
    - name: Validate Markdown files
      run: |
        echo "=== MARKDOWN VALIDATION ==="
        for file in $(find . -name "*.md"); do
          echo "Checking $file..."
          if [ -s "$file" ]; then
            echo "✅ $file is valid (not empty)"
          else
            echo "❌ $file is empty"
          fi
        done 